name: Deploy Frontend to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout frontend code
      - name: Checkout frontend code
        uses: actions/checkout@v3

      # 2️⃣ Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/212643517584/locations/global/workloadIdentityPools/github-actions-pool-v2/providers/github-frontend-provider
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      # 3️⃣ gcloud & kubectl kurulumu
      - name: Set up gcloud & kubectl
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: kubectl

      # 4️⃣ Docker image build & push
      - name: Build & Push Frontend Docker
        run: |
          IMAGE_TAG=gcr.io/${{ secrets.GCP_PROJECT }}/socialmedia-frontend:${GITHUB_SHA}
          echo "Building Docker image with tag $IMAGE_TAG"
          gcloud builds submit --tag $IMAGE_TAG

      # 5️⃣ GKE credentials al
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials socialmedia-cluster --zone asia-east1-a

      # 6️⃣ Deploy Frontend & Ingress
      - name: Deploy Frontend & Ingress
        run: |
          IMAGE_TAG=gcr.io/${{ secrets.GCP_PROJECT }}/socialmedia-frontend:${GITHUB_SHA}
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/ingress.yaml
          # Commit-SHA tag ile image güncelle
          kubectl set image deployment/socialmedia-frontend-x frontend=$IMAGE_TAG
          # 60 saniye rollout kontrol, başarısızsa rollback
          kubectl rollout status deployment/socialmedia-frontend-x --timeout=60s || \
          kubectl rollout undo deployment/socialmedia-frontend-x
