name: Deploy Frontend & Backend to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend code
        uses: actions/checkout@v3
        with:
          path: backend

      - name: Authenticate to GCP via Workload Identity
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER_BACKEND }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Build & Push Backend Docker image
        run: |
          cd backend
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/socialmedia-backend

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy socialmedia-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/socialmedia-backend \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated \
            --add-cloudsql-instances ${{ secrets.GCP_PROJECT }}:asia-east1:socialmedia-instance \
            --set-env-vars DATABASE_HOST=/cloudsql/${{ secrets.GCP_PROJECT }}:asia-east1:socialmedia-instance,DATABASE_USER=postgres,DATABASE_PASSWORD=654321Aa!,DATABASE_NAME=socialmedia

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v3
        with:
          path: frontend

      - name: Authenticate to GCP via Workload Identity
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER_FRONTEND }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Build & Push Frontend Docker image
        run: |
          cd frontend
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/socialmedia-frontend

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy socialmedia-frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/socialmedia-frontend \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated \
            --set-env-vars REACT_APP_API_URL=https://socialmedia-backend-${{ secrets.GCP_PROJECT }}.asia-east1.run.app
