name: Deploy Frontend to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v3
        with:
          path: frontend

      - name: Authenticate to GCP via Workload Identity
        uses: google-github-actions/auth@v1
        with:
          # Bu değeri tam resource adıyla güncelle
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/frontend-pool/providers/frontend-provider
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Build & Push Frontend Docker image
        run: |
          cd frontend
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/socialmedia-frontend

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy socialmedia-frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/socialmedia-frontend \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated \
            --set-env-vars REACT_APP_API_URL=https://socialmedia-backend-${{ secrets.GCP_PROJECT }}.asia-east1.run.app
