name: Deploy Frontend to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v3
        with:
          path: frontend

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/212643517584/locations/global/workloadIdentityPools/github-actions-pool-v2/providers/github-frontend-provider
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up gcloud & kubectl
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_kubectl: true

      - name: Build & Push Frontend Docker
        run: |
          cd frontend
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/socialmedia-frontend

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials socialmedia-cluster --zone asia-east1-a

      - name: Deploy Frontend & Ingress
        run: |
          kubectl apply -f frontend/kubernetes/frontend-deployment.yaml
          kubectl apply -f kubernetes/ingress.yaml
