name: Deploy Frontend & Backend to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend code
        uses: actions/checkout@v3
        with:
          path: backend

      - name: Authenticate to GCP via Workload Identity
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/212643517584/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "github-actions-deploy@pure-highlander-471707-t2.iam.gserviceaccount.com"

      - name: Build & Push Backend Docker image
        run: |
          cd backend
          gcloud builds submit --tag gcr.io/pure-highlander-471707-t2/socialmedia-backend

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy socialmedia-backend \
            --image gcr.io/pure-highlander-471707-t2/socialmedia-backend \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated \
            --add-cloudsql-instances pure-highlander-471707-t2:asia-east1:socialmedia-instance \
            --set-env-vars DATABASE_HOST=/cloudsql/pure-highlander-471707-t2:asia-east1:socialmedia-instance,DATABASE_USER=postgres,DATABASE_PASSWORD=654321Aa!,DATABASE_NAME=socialmedia

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v3
        with:
          path: frontend

      - name: Authenticate to GCP via Workload Identity
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/212643517584/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "github-actions-deploy@pure-highlander-471707-t2.iam.gserviceaccount.com"

      - name: Build & Push Frontend Docker image
        run: |
          cd frontend
          gcloud builds submit --tag gcr.io/pure-highlander-471707-t2/socialmedia-frontend

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy socialmedia-frontend \
            --image gcr.io/pure-highlander-471707-t2/socialmedia-frontend \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated \
            --set-env-vars REACT_APP_API_URL=https://socialmedia-backend-212643517584.asia-east1.run.app
